---
apiVersion: v1
kind: Secret
metadata:
  name: watashi93-watashi93-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23Janus1/watashi93-gateway-gitops
